### PR TITLE
Latexfied and Jaxified iris_logreg.ipynb

### PR DESCRIPTION
**Pull request by rohit-khoiwal-30**
### Figure Number
Book1 - 10.1

### Figures
| Before PR | 10 1_before_pr |
| :-: | :-: |
| After PR | fig10 1 b_latexified |

### Issue 
#878 

## Steps
- [x] Implement logistic regression from scratch using JAX.
- [x] Added Interactive Contour plot.
- [x]  Latexified the figures.

## Checklist

- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

### CODE REVIEW

**Comment by karm-patel** [comment]
Dr. @murphyk, Since this is a notebook we can not directly import this code. So we were thinking to make `.py` which can have helper functions (including `fit()`) of first-order implementation of Logistic regression and we can put this `.py` in `probml_utils`. 

Also, @rohit-khoiwal-30 is working on a second-order method for logistic regression once he is done, he can add `.py` for second-order also.  Will this be useful?

**Comment by murphyk** [comment]
Yes, we should factor out logreg_fit.py and add to probml_utils. You should also add a unit test that compares its output to sklearn, similar to what I did in  https://github.com/probml/pyprobml/blob/master/notebooks/book1/08/opt_jax.ipynb.

**Comment by murphyk** [comment]
This is blocked on https://github.com/probml/probml-utils/pull/18

**Comment by karm-patel** [comment]
> This is blocked on [probml/probml-utils#18](https://github.com/probml/probml-utils/pull/18)

Yes Sir, @rohit-khoiwal-30 is working on this.

**Comment by murphyk** [comment]
Code LGTM but it is failing the first 2 checks.

**Comment by rohit-khoiwal-30** [comment]
> Code LGTM but it is failing the first 2 checks.

I have updated my local branch. Now it's passing the first 2 checks also.
@murphyk

**Pull request merged**
