### PR TITLE
Added implementation of bootstrapDemoBer

### LINKED ISSUE #113: Convert bootstrapDemoBer to python
Test body
This is figure number 4.23 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/bootstrapDemoBer.m)

### LINKED ISSUE #180: Convert bootstrapDemoBer to python
This is figure number 4.23 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/bootstrapDemoBer.m)

### PR DESCRIPTION
**Pull request by animesh-007**
Added python implementation of bootstrapDemoBer.
Fixes #180 
Figure_1
Figure_2
Figure_3
Figure_4

### CODE REVIEW

**Review by mjsML — CHANGES_REQUESTED** [review]
Can you try to make the bars the same width across the figures for consistency? Also 3 decimal points for variables on the labels are more than enough as per the original figures 🙂

**Comment by animesh-007** [comment]
> Can you try to make the bars the same width across the figures for consistency? Also 3 decimal points for variables on the labels are more than enough as per the original figures 🙂

Made suggested changes.

**Comment by animesh-007** [comment]
I also tried to merge my 3 commits but it made a total of 4 commits in this PR now.😓

**Comment by mjsML** [comment]
> I also tried to merge my 3 commits but it made a total of 4 commits in this PR now.

No worries, just update the images in the description please.

**Review by mjsML — APPROVED** [review]

**Comment by animesh-007** [comment]
> > I also tried to merge my 3 commits but it made a total of 4 commits in this PR now.
> 
> No worries, just update the images in the description please.

Done.😇

**Pull request merged**
