### PR TITLE
Convert_gprdemochangehparams_to_python

### PR DESCRIPTION
**Pull request by Drishttii**
@mjsML and @murphyk, please review the code. Thanks :)

#220 

Figures generated:

a) Fig. 17.9 (a)
Plot-0

b) Fig. 17.9 (b)
Plot-1

c) Fig. 17.9 (c)
Plot-2

### CODE REVIEW

**Review by murphyk — CHANGES_REQUESTED** [review]
I'm confused why you use covSEiso+covNoise to generate the training data, but then use a different RBF kernel to fit the data. Can you not use the same kernel for both? Also why do you need sklearn GP and Gpy?

**Comment by Drishttii** [comment]
Thank you for the review. The function covSEiso is basically generating datapoints from an RBF kernel with parameters l=1.0, sigma_f=1.0 and since we need noisy datapoints I used covNoise with sigma_y=0.1 (as mentioned in the book and the matlab code). So, covSEiso and covNoise are made just for the sake of doing them. Now I am generating data normally. Also, yes the sklearn imports were not required. Thanks again :)

**Comment by murphyk** [comment]
This is much simpler now - thanks!

**Comment by Drishttii** [comment]
Thank you very much :)

**Pull request merged**
