### PR TITLE
Converted mixBerMnistEM to python

### LINKED ISSUE #174: Convert mixBerMnistEM to python
This is figure number 21.19 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/mixBerMnistEM.m)

### PR DESCRIPTION
**Pull request by shivaditya-meduri**
mixBernoulliMnist

Closes #174 

The code might take some time to load and this is because it is downloading the MNIST dataset from online and the delay in execution is solely due to this and not due to the inefficiency of the code.

The values and the images will differ because the data is randomly chosen from the total set of images.

I initially added +1 to all images in the training set and changed the Bernoulli function to adapt to this, but did not see any change in the execution, It was more convenient for me to use the binary image as is and use the implementation of Bernoulli distribution which is used for this mixture model.

In this implementation, I did not find the optimal k because the optimal k=20 has already been found through trial and error in the MATLAB code and no graph implementation is found in the book.

### CODE REVIEW

**Comment by shivaditya-meduri** [comment]
@murphyk and @mjsML, please review this PR.

**Review by mjsML — APPROVED** [review]

**Comment by shivaditya-meduri** [comment]
Please ignore the 2nd commit, it is associated with another issue

**Comment by mjsML** [comment]
@shivaditya-meduri , backup your work for both PRs, then, create a new branch **per issue** then create new PRs based on two branches, now this PR has two commits to two separate files.

**Comment by shivaditya-meduri** [comment]
Thank you for your patience @mjsML

**Pull request closed without merging**
