### PR TITLE
Convert twoPowerCurves(Fig 5.15 (b)) to python/JAX

### PR DESCRIPTION
**Pull request by Garvit9000c**
index

### CODE REVIEW

**Review by mjsML — CHANGES_REQUESTED** [review]
@Garvit9000c Please close this pull request and create a new one with only one file change with a single commit.

**Comment by Garvit9000c** [comment]
ohk Sir!

**Comment by mjsML** [comment]
@Garvit9000c Please add the first (figure 5.15 (a))

**Comment by Garvit9000c** [comment]
The Matlab code contains only 5.15 (b) in the issue!

**Comment by Garvit9000c** [comment]
Ok Sir, now i will convert part(a), and for part (b) i have created a pull request with 1 commit, 1file change.

**Pull request closed without merging**
