### PR TITLE
Converted gaussInterpDemoStable to python

### PR DESCRIPTION
**Pull request by ashishpapanai**
#### Generates: figure number 17.1
Closes: #216 

gaussInterpNoisyDemoStable_obsVar0_priorVar1
gaussInterpNoisyDemoStable_obsVar0_priorVar10
gaussInterpNoisyDemoStable_obsVar100_priorVar1
gaussInterpNoisyDemoStable_obsVar100_priorVar10

### CODE REVIEW

**Comment by ashishpapanai** [comment]
@mjsML  Please review the PR.

**Review by murphyk — CHANGES_REQUESTED** [review]
Please avoid hard-coding numbers like 141 or 151 in the body of the code - define in terms of n and m.
Please avoid doubly nested for-loops (for i, for j).
Please draw 3 samples, not 2 :)
Please refactor your demo() function so that the noise-free code is one function,
and the noisy code (obs_var>0) is another. (You can simplify the filenames for these 2 cases, as well :)

**Comment by ashishpapanai** [comment]
Hello @murphyk,
Fixed all changes, Please review the PR.

**Comment by murphyk** [comment]
Please avoid hard-coding magic constants, eg in the the line below, what is 302? It should be computed!
```
 f = np.concatenate((part1, part2)).reshape(302, 1)
```
(This is a common mistake you make)

**Comment by murphyk** [comment]
This is also bad style
```
 x = 141
    Sigma[0: x, 0:x] = inverseB11[0: x, 0:x]
```

**Comment by murphyk** [comment]
Finally, your code may have a bug. The figure looks very different to the matlab code (qualitatively), even I change the random seed. Please investigate. (I think it is related to boundary conditions)

**Pull request merged**
