### PR TITLE
biasVarModelComplexityV3

### LINKED ISSUE #182: Convert biasVarModelComplexity3 to python
This is figure number 4.25 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/biasVarModelComplexity3.m)

### PR DESCRIPTION
**Pull request by nappaillav**
Created Bias Variance Model Complexity plot
Closes #182

image
@mjsML @murphyk

### CODE REVIEW

**Comment by mjsML** [comment]
Can I ask you to please pick colors from [matplotlib's viridis](https://matplotlib.org/stable/tutorials/colors/colormaps.html) colormap please? context: [updated contribution guidelines](https://github.com/probml/pyprobml/blob/master/CONTRIBUTING.md).

**Review by mjsML — CHANGES_REQUESTED** [review]
Can I ask you to please pick colors from [matplotlib's viridis](https://matplotlib.org/stable/tutorials/colors/colormaps.html) colormap please? context: [updated contribution guidelines](https://github.com/probml/pyprobml/blob/master/CONTRIBUTING.md).

**Comment by nappaillav** [comment]
I using the default cmap. @mjsML .
image

**Comment by mjsML** [comment]
@nappaillav , because the left figures are more than few colors, you would have to manually specify viridis. for context you can watch the video in the matplotlib help article linked above.

**Comment by nappaillav** [comment]
Updated the colormap. @mjsML 
image

Here is the list of colors that can be differentiated by color blind people. 
Either they can use default settings or set it manually by using these

```
CB_color_cycle = ['#377eb8', '#ff7f00', '#4daf4a',
                  '#f781bf', '#a65628', '#984ea3',
                  '#999999', '#e41a1c', '#dede00']
```
If you want we can update this list in the contribution guide lines.

**Review by mjsML — APPROVED** [review]

**Pull request merged**
