### PR TITLE
Added script for vector quantization figures

### PR DESCRIPTION
**Pull request by animesh-007**
Added `vqDemo.py` script for vector quantization figures.
Solves issue #236

### CODE REVIEW

**Comment by mjsML** [comment]
@animesh-007 can I ask you to kindly include a screenshot of the figure it produced. I tested this and it works, the picture is different than the one in the book :) @murphyk should be aware of this :)

**Review by mjsML — APPROVED** [review]
The picture quantized is different FYI

**Comment by animesh-007** [comment]
> The picture quantized is different FYI

Will this picture work or should I use the same clown picture?

**Comment by mjsML** [comment]
> > The picture quantized is different FYI
> 
> Will this picture work or should I use the same clown picture?

I'm not sure that is up to the author 🙂  ... I verified your code works. I believe @murphyk would not mind unless there is like a copyright / non technical reason ... but in concept your code should handle any image 🙂

**Comment by animesh-007** [comment]
> > > The picture quantized is different FYI
> > 
> > 
> > Will this picture work or should I use the same clown picture?
> 
> I'm not sure that is up to the author 🙂 ... I verified your code works. I believe @murphyk would not mind unless there is like a copyright / non technical reason ... but in concept your code should handle any image 🙂

Cool. Do let me know if you want any changes to this.😇

**Review by murphyk — APPROVED** [review]

**Pull request merged**
