### PR TITLE
Refactor Fig 23.3 Two Moons normalizing flow

### PR DESCRIPTION
**Pull request by vz415**
Added CNF and made figure show progression of sampled flow.

### Figure Number

book2 - 23.3

### Figures

| Old | New |
| :-: | :-: |
| OldFigure_23.3 | New|

### Issue 

[#938](https://github.com/probml/pyprobml/issues/938#issuecomment-1166956742)

## Checklist

- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

## Potential problems/Important remarks

Created a new notebook with both NSF and CNF normalizing flow examples, and left the original [two_moons_normalizing_flow.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book2/23/two_moons_normalizing_flow.ipynb) in place. Let me know if this will work and if I should reformat or reseize the figure.

### CODE REVIEW

**Comment by murphyk** [comment]
Please split this into 2 notebooks, one for NSF (neural spline flow) and one for CNF (continious neural flow).
Also please follow formatting conventions at https://github.com/probml/pyprobml/tree/master/notebooks, and use pml.savefig instead of plt.savefig.

**Comment by murphyk** [comment]
Hi @vz415 . Any progress on this? splitting notebook into 2 should be quick and easy. I'd like to include some of these figures in the book and I'm going to press soon!

**Comment by vz415** [comment]
@murphyk oh! Sorry, I had to prep and travel for icml. I'll make the modified pull request tomorrow (Monday).

**Comment by vz415** [comment]
Ok, the latest commits split the notebook and created figures that are appropriately labeled. Let me know if there is anything else I need to do for the figures. Thanks

**Pull request merged**
