### PR TITLE
Convert fisherLDAdemo to python

### PR DESCRIPTION
**Pull request by Drishttii**
@murphyk and @mjsML,  please review the code.

#197 

Figures generated:

a) Fig. 9.4

FischerLDA_and_PCA_vectors

b) Fig. 9.5 (a)

Projection_of_points_on_fisher_vec

c) Fig. 9.5 (b)

Projection_of_points_on_pca_vec

Also, shall I delete the .pynb file?

### CODE REVIEW

**Review by mjsML — CHANGES_REQUESTED** [review]
Please remove the ipynb file.
Your pull should contain the py file used to create the figures for now.

**Comment by Drishttii** [comment]
Removed the .ipynb file. Thanks.

**Review by murphyk — CHANGES_REQUESTED** [review]
I like that you implement both methods using sklearn and 'from scratch'. It would be even better if you check automatically that they give the same results. Also please refactor so the plotting code is shared across both methods. So the code should look something like this (where results is the relevant output):
```
results_flda_sklearn = flda_sklearn(data)
results_flda_manual = flda_manual(data)
assert np.allclose(results_flda_sklearn, results_flda_manual))
plot_results(results_flda_sklearn)

// repeat above using pca
```
 

```

**Comment by Drishttii** [comment]
Thank you for your comments. I have made the suggested changes, please let me know if anything else is required.
@murphyk @mjsML

**Comment by murphyk** [comment]
This is great. Next time please use `assert np.allclose(...)` instead of print statements :)

**Comment by murphyk** [comment]
Also, if the matlab files is `fisherLDAdemo.m`, please call the python file `fisherLDAdemo.py`, since it is meant to be a drop-in replacement. (You named your file `convert_fisherldademo_to_python.py`!)

**Comment by murphyk** [comment]
Also, please use `np.random.state(0)` for reproducibility.

**Comment by Drishttii** [comment]
Thank you very much. I will keep these suggestions in mind :)

**Pull request merged**
