### PR TITLE
Refactor notebooks/nmt_torch.ipynb

### LINKED ISSUE #386: Refactor notebooks/nmt_torch.ipynb
Refactor `notebooks/nmt_torch.ipynb` by removing the use of the d2l library.

### PR DESCRIPTION
**Pull request by Nirzu97**
@murphyk , @mjsML  Please review this.

closes #386 

Colab link: https://colab.research.google.com/github/Nirzu97/pyprobml/blob/nmt-torch/notebooks/nmt_torch.ipynb

### CODE REVIEW

**Comment by animesh-007** [comment]
@Nirzu97 Could you also add a link to a Colab notebook?

**Comment by Nirzu97** [comment]
@animesh-007 Done.

**Comment by murphyk** [comment]
Please add 
```
Based on sec 9.7 of http://d2l.ai/chapter_recurrent-modern/seq2seq.html
```

**Comment by Nirzu97** [comment]
@murphyk I have made the changes. Please review it.

**Pull request merged**
