### PR TITLE
rotation demo with pretty print matrix function.

### PR DESCRIPTION
**Pull request by andrewnc**

### CODE REVIEW

**Comment by murphyk** [comment]
i get this error


  File "/Users/kpmurphy/github/pyprobml/book/rotation_demo.py", line 17, in
<module>
    matprint(R)

  File "/Users/kpmurphy/github/pyprobml/book/rotation_demo.py", line 8, in
matprint
    print(("{:"+str(col_maxes[i])+fmt+"}").format(y), end="  ")

TypeError: 'str' object is not callable

**Comment by andrewnc** [comment]
What version of python did you use?

**Comment by murphyk** [comment]
i always use python 3

**Comment by andrewnc** [comment]
Sorry, I mean are you using 3.5 or 3.6?

**Comment by andrewnc** [comment]
I'll dig into it and see what I can find.

**Comment by andrewnc** [comment]
see #50 for update

**Comment by murphyk** [comment]
yes, that works, thanks.
(FYI I'm using python 3.7)

**Pull request merged**
