### PR TITLE
Added script for central limit theorem plots

### PR DESCRIPTION
**Pull request by animesh-007**
@murphyk  Added central limit theorem plots script for #99.
Figure_1
Figure_2

### CODE REVIEW

**Comment by mjsML** [comment]
Hi @animesh-007 can I ask you to please rename the file to centralLimitDemo.py ?

**Comment by animesh-007** [comment]
> Hi @animesh-007 can I ask you to please rename the file to centralLimitDemo.py ?

Done.

**Comment by mjsML** [comment]
Looks good to me, @murphyk What do you think?

**Review by mjsML — APPROVED** [review]

**Comment by mjsML** [comment]
closes #103

**Review by murphyk — APPROVED** [review]

**Pull request merged**
