### PR TITLE
Mixture of Bernoulli using Stochastic Variational Inference

### LINKED ISSUE #348: make JAX implementation of SVI for mixture models
Stochastic Variational Inference can be used to do online optimization of Bayesian/latent variable models, such as finite mixtures of Gaussians / Bernoullis - this is faster than batch EM for large datasets. [Here](https://brendanhasz.github.io/2019/06/12/tfp-gmm.html) is an implementation of SVI for GMMs in Tensorflow Probabiltity. The goals of this issue are:
1. make a JAX translation of this code, using the new [distrax library](https://github.com/deepmind/distrax).
2. generalize the code to work with mixtures of Bernoullis, apply it to the same binarized MNIST data used in [mixBerMNIST.py](https://github.com/probml/pyprobml/blob/master/scripts/mixBerMnistEM.py)

### PR DESCRIPTION
**Pull request by shivaditya-meduri**
Closes #348
This is a draft
[VarInf for MixBern.pdf](https://github.com/probml/pyprobml/files/6385065/VarInf.for.MixBern.pdf)
[Bayesian_Estimation_of_Beta_Mixture_Models_with_Va.pdf](https://github.com/probml/pyprobml/files/6385068/Bayesian_Estimation_of_Beta_Mixture_Models_with_Va.pdf)
I am trying to implement the model using the above 2 research papers as a reference.

### CODE REVIEW

**Comment by shivaditya-meduri** [comment]
@Nirzu97 , I am currently stock on training the model and parameter initialization, I would recommend you to try to initialize various parameters for variational distribution, priors, batch size, training images....

**Comment by shivaditya-meduri** [comment]
The ideal output would plot cluster means which look like digits of MNIST, instead of gibberish that it is plotting now

**Comment by Nirzu97** [comment]
Thank you I will look into it.

**Comment by Nirzu97** [comment]
@shivaditya-meduri  This code is almost same as given in the link by murphy. Where is the JAX implementation?

**Comment by shivaditya-meduri** [comment]
> @shivaditya-meduri  This code is almost same as given in the link by murphy. Where is the JAX implementation?

I will upload the complete implementation today, I trained the model successfully and found the ideal parameters. Thank you

**Pull request closed without merging**
