### PR TITLE
Converted logregLaplaceGirolamiDemo to python

### LINKED ISSUE #201: Convert logregLaplaceGirolamiDemo to python
This is figure number 10.15 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/logregLaplaceGirolamiDemo.m)

### PR DESCRIPTION
**Pull request by shivaditya-meduri**
Closes #201
This code is for figures 10.14 and 10.15 in the book
As the data is generated randomly, graphs might not look exactly similar but the same mathematics is used to create these graphs
Issue : Convert logregLaplaceGirolamiDemo to python #201

logregLaplaceGirolamiDemo_LaplaceApproximationtoPosterior
logregLaplaceGirolamiDemo_logitprob
logregLaplaceGirolamiDemo_LogLikelihood
logregLaplaceGirolamiDemo_LogUnnormalisedPosterior
logregLaplaceGirolamiDemo_MonteCarloApprox
logregLaplaceGirolamiDemo_preddistlogit
logregLaplaceGirolamiDemo_data
logregLaplaceGirolamiDemo_decisionboundarysampledw

### CODE REVIEW

**Comment by shivaditya-meduri** [comment]
@murphyk  and @mjsML. Please review this PR.

**Review by murphyk — CHANGES_REQUESTED** [review]
Please avoid hard-coding magic numbers like `t.reshape((60))'
(I assume 60=N*nclasses=30*2?)

**Comment by murphyk** [comment]
It is odd that your sampled decision boundaries do not spread out as much as those from my matlab code, and consequently the averaged decision boundary  is almost linear, and not curvy. Please can you investigate why. (Is it a mixup between precision and covariance matrix? Or sigma^2 vs sigma?)

**Comment by shivaditya-meduri** [comment]
Hi @murphyk , I changed the seed value to the random number generator and it seems to create decision boundaries which are more spread out. I have inverted the covariance matrix to generate the laplace aproximation and used it for sampling too as per the book 
"the Laplace approximation approximates the posterior using a Gaussian.
The mean of the Gaussian is equal to the MAP estimate  and the covariance is equal to the inverse
Hessian H computed at the MAP estimate"
If you think I have given any inputs erroneously please let me know and I will make the changes.
Sorry for not ensuring this in my previous commit, I realize that you are very busy and I appreciate your patience in reviewing my code.

**Comment by murphyk** [comment]
Looks good to me :)

**Pull request merged**
