### PR TITLE
Converted hclustYeastDemo.m to python

### LINKED ISSUE #234: Convert hclustYeastDemo to python
This is figure number 21.6 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/hclustYeastDemo.m)

### PR DESCRIPTION
**Pull request by ashishpapanai**
Converted the code [here](https://github.com/probml/pmtk3/blob/master/demos/hclustYeastDemo.m) to create figure number 21.6. 
Closes #234 
Figure_1
Figure_3
clusterYeastCompleteLink
clusterYeastSingleLink
clusterYeastAvgLink

### CODE REVIEW

**Comment by ashishpapanai** [comment]
Hello @murphyk, The plot generated is slightly different as compared to the plot generated in version 1 of the book, this might be due to the difference in the algorithm used in the MATLAB implementation and the Python implementation by me. 
Is it fine or should I rework by coding the algorithm from scratch?

**Review by mjsML — CHANGES_REQUESTED** [review]
Hi @ashishpapanai thanks for the PR.
Few changes:
- Can I ask you to please use 
standard scipy mat file loader like so for this and the other PR your submitted.
```python 
import scipy.io
mat = scipy.io.loadmat('foo.mat')
```
- exclude the .gitignore and the update to the png and .mat files?

**Comment by ashishpapanai** [comment]
> Hi @ashishpapanai thanks for the PR.
> Few changes:
> 
> * Can I ask you to please use
>   standard scipy mat file loader like so for this and the other PR your submitted.
> 
> ```python
> import scipy.io
> mat = scipy.io.loadmat('foo.mat')
> ```
> 
> * exclude the .gitignore and the update to the png and .mat files?

1. Used Scipy mat loader. 
2. Excluded png files, git ignore and .mat files.

It took a lot of commits trying out various fixes for removing the files, Apologies for the inconveniences.

**Comment by mjsML** [comment]
@ashishpapanai forgive me, I thought you were overriding the mat file with this change, turns out it's missing from pyprobml and it does exist on pmtk3 ... I added the matfile ... This currently works error free in colab.

**Review by mjsML — APPROVED** [review]

**Comment by murphyk** [comment]
This LGTM, but the [original matlab script](https://github.com/probml/pmtk3/blob/master/demos/hclustYeastDemo.m) also generated fig 21.4 (the 3 dendograms). Please add that too.

**Comment by ashishpapanai** [comment]
Done @murphyk

**Comment by murphyk** [comment]
FYI, I had to add truncate_mode='lastp' as an argument to make it visually match matlab...

**Pull request merged**
