### PR TITLE
Converted logregLaplaceGirolamiDemo to python 

### LINKED ISSUE #201: Convert logregLaplaceGirolamiDemo to python
This is figure number 10.15 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/logregLaplaceGirolamiDemo.m)

### PR DESCRIPTION
**Pull request by ashishpapanai**
### Generates: figure number 10.14 & 10.15
Closes #201

logregLaplaceGirolamiData
logregLaplaceGirolamiPrior
logregLaplaceGirolamiNLL
logregLaplaceGirolamiPost

### CODE REVIEW

**Comment by ashishpapanai** [comment]
@murphyk @mjsML, The following lines use files present in MATLAB tools, 
```
pp =  preprocessorCreate('addOnes', false, 'standardizeX', false);
model = logregFitBayes(X, t, 'method', 'laplace', 'lambda', 1/alpha, 'preproc', pp);
```
I am unable to find a python equivalent for the same, and converting each MATLAB file in a single file will make the code way too big and it won't be reusable as well. Should I work on converting the files in MATLAB Tools to python or Could you please suggest any python equivalent if you know any?

**Comment by murphyk** [comment]
The preprocessorCreate is just like skearn pipeline. In this case, the matlab code does not preprocessing,
so you can ignore it. As for logregFitBayes, you can find a Python version here:
https://bayes-logistic.readthedocs.io/en/latest/usage.html
(I have not tried it, not sure if it works.)

**Comment by murphyk** [comment]
Please avoid hard-coding 'magic numbers; like 25291 in the line below
```
Log_Prior = Log_Prior.reshape((25921, 1))
```
I

**Comment by ashishpapanai** [comment]
Tried, It doesn't solve the purpose of getting 
```
wMAP = model.wN;
C = model.VN; 
```

**Comment by murphyk** [comment]
Ok, well you'll just have to write the code from first principles (converting math to numpy :)

**Pull request closed without merging**
