### PR TITLE
Converted VAE celeba demo  to pytorch

### LINKED ISSUE #360: convert VAE celeba demo from TF2 to pytorch and/or JAX
Convert [vae_celeba_tf.ipynb](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/vae_celeba_tf.ipynb) to pytorch and/or JAX.
Also convert [vae_mnist_gdl_tf.ipynb](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/vae_mnist_gdl_tf.ipynb).
(Why do we have 2 demos?)
Note: code should work for any kind of image, eg gray scale MNIST or color celebA, so don't hard-code image dimensions into the model.

### PR DESCRIPTION
**Pull request by always-newbie161**
Closes  #360
@murphyk, @mjsML please review the code
I converted the first notebook, the status is that all the model creation, reconstructions, analysis are successfully built but the **model training** is not going as expected. The losses are higher than in the tensorflow one.
As of now, I couldn't find the errors if any, I request you to review this code and give suggestions
colab link:
https://colab.research.google.com/drive/1ZJbWoLQOfo0INvD_mSbIwMwmdRzN78Mt?usp=sharing

### CODE REVIEW

**Comment by murphyk** [comment]
I'm not sure why your code does not train well. Maybe start with an existing CVAE implementation in Python (eg [this one](https://debuggercafe.com/convolutional-variational-autoencoder-in-pytorch-on-mnist-dataset/)) for MNIST, and then gradually modify it to work with celeba and do all that other stuff (eg interpolation). ie the model does not need to be identical to the TF one.

**Comment by always-newbie161** [comment]
@murphyk, Apologies for a late response, changed the model to work both with mnist and celeba with custom layers as in the tf one, last time I tried to do the same thing but what I have learnt is that pytorch needs "nn.ModuleList" to create a list of nn layers instead of a  python list. 

Thanks for the above link, it helped in making the code  and model more clear.

**Comment by murphyk** [comment]
I don't know why you have 2 notebooks attached to this PR - which one should I use?

Anyway, I tried to run `vae_mnist_celeba` in colab (with GPU) but get this error
`
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-0401a2f4298d> in <module>()
      5 models_celeba['200d-stoch'] = ConvVAE(Xsmall.shape,encoder_conv_filters,decoder_conv_t_filters,200,'200d-stoch')
      6 models_celeba['200d-det'] = ConvVAE(Xsmall.shape,encoder_conv_filters,decoder_conv_t_filters,200,'200d-det',True)
----> 7 summary(models_celeba['200d-det'],Xsmall.shape)

7 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight, bias)
    394                             _pair(0), self.dilation, self.groups)
    395         return F.conv2d(input, weight, bias, self.stride,
--> 396                         self.padding, self.dilation, self.groups)
    397 
    398     def forward(self, input: Tensor) -> Tensor:

RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

I also tried running `vae_celeba_mnist_torch`. This seems to work so far (it's still running...)

**Comment by always-newbie161** [comment]
@murphyk  Sorry, I thought to replace the first one but I messed up with the names, Please consider "vae_celeba_mnist.ipynb"  in the repo(the one you got the error with) . The error probably is due to running in GPU, I will look into it, actually I got limited with my GPU usage in colab So i was testing it normally(without GPU)

**Comment by murphyk** [comment]
this is so much faster - thanks!

**Pull request merged**
