### PR TITLE
Converted postDensityIntervals to python

### PR DESCRIPTION
**Pull request by ashishpapanai**
#### Generates figure: 4.19
Closes: #179 
centralInterval
HPD

### CODE REVIEW

**Comment by ashishpapanai** [comment]
@mjsML, The number of commits is increased due to the inclusion of some unnecessary files, Please Squash and Merge if the number of commits is an issue.

**Comment by ashishpapanai** [comment]
Ready for review @mjsML, @murphyk, Please review the PR.

**Comment by mjsML** [comment]
> @mjsML, The number of commits is increased due to the inclusion of some unnecessary files, Please Squash and Merge if the number of commits is an issue.

I didn't know github supported this 🙂 !
@murphyk I disabled the normal merges from the [settings](https://docs.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests) FYI.

**Review by mjsML — CHANGES_REQUESTED** [review]
Can I ask you to please shift both figures to align with the Y-axis 0 as per the original figure in the book?

**Comment by ashishpapanai** [comment]
Fixed @mjsML

**Comment by mjsML** [comment]
> Fixed @mjsML

@ashishpapanai You didn't push the change :)

**Comment by ashishpapanai** [comment]
My bad, Done. @mjsML.

**Comment by ashishpapanai** [comment]
Done @mjsML. I am sorry for the inconveniences.

**Review by mjsML — APPROVED** [review]

**Comment by mjsML** [comment]
@ashishpapanai Please make sure you use [math expressions](https://matplotlib.org/stable/tutorials/text/mathtext.html) where possible.

**Comment by ashishpapanai** [comment]
Noted. I was following Unicode till now. I'll switch to math, Should I do this for this PR as well? @mjsML

**Comment by mjsML** [comment]
Look again, I added it on the pull already, since it's a minor change.

**Comment by ashishpapanai** [comment]
@mjsML, Are there new issues coming up fro GSOC?

**Comment by mjsML** [comment]
@ashishpapanai don't worry about GSOC having new issues ... there are tons to do for the entire period of the summer. The core overall objective is to make sure there are examples of the entire book series in code (book 2 is still being written so there are a lot more figures there, but not shared publicly yet). 

There is also project 2 which is the JAX notebooks (supplementary material to the book series offering of theory and figures) e.g. JAX notebooks. since JAX and co (Flax, RLax, haiku ..etc) are still quite young, and LAX/JAX give you a finer grain control over how things are done, it's an amazing opportunity to learn (and teach others via your contributions) PML.

I hope this helped.

**Comment by animesh-007** [comment]
> @ashishpapanai don't worry about GSOC having new issues ... there are tons to do for the entire period of the summer. The core overall objective is to make sure there are examples of the entire book series in code (book 2 is still being written so there are a lot more figures there, but not shared publicly yet).
> 
> There is also project 2 which is the JAX notebooks (supplementary material to the book series offering of theory and figures) e.g. JAX notebooks. since JAX and co (Flax, RLax, haiku ..etc) are still quite young, and LAX/JAX give you a finer grain control over how things are done, it's an amazing opportunity to learn (and teach others via your contributions) PML.
> 
> I hope this helped.

I wanted to ask one small thing. Could we submit one proposal for both the projects or do we need to submit one proposal for each?

**Comment by murphyk** [comment]
For GSOC, you should apply to the 'convert matlab figures' project, since that is the top priority. As Mahmoud said, there will many more such examples for vol 2, coming later this Spring; some of these will need JAX. The 'conversion of TF to JAX' project is lower priority, but we'll hopefully get to that later this summer -  So the 2 projects are really one, to be done in sequence :)

**Pull request merged**
