### PR TITLE
Added JAX GAN demo in Colab

### PR DESCRIPTION
**Pull request by susnato**
## Description
Added JAX GAN demo in Colab

### Issue 

https://github.com/probml/pyprobml/issues/675

## Checklist:

- [✅] Performed a self-review of the code
- [✅] Tested on Google Colab.

### CODE REVIEW

**Comment by susnato** [comment]
Can you please review my code? @mjsML @murphyk

**Comment by mjsML** [comment]
Hi @susnato ,
Thank you for the PR, it's not viewable via GitHub for us.
Can I ask you to please create a new PR, convert this into .py for code and a scratch external colab to test it with (shared publicly). 
Thanks

**Comment by susnato** [comment]
Ok I will do it as soon as possible btw till then you can view it here , https://github.com/susnato/pyprobml/blob/master/JAX%20GAN%20demo%20in%20Colab.ipynb
It's in my forked repository.

**Comment by susnato** [comment]
@mjsML I am closing this PR then and opening another one.

**Pull request closed without merging**
