### PR TITLE
Converted kernelBinaryClassifDemo to python

### LINKED ISSUE #223: Convert kernelBinaryClassifDemo to python
This is figure number 17.22 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/kernelBinaryClassifDemo.m)

### PR DESCRIPTION
**Pull request by always-newbie161**
Figures:

logregL2
Screenshot 2021-03-24 at 9 52 03 PM

logregL1
(I used confidence scores to get support vectors)
Screenshot 2021-03-24 at 9 52 17 PM

RVM
Screenshot 2021-03-24 at 9 52 31 PM

SVM
(I chose the 'C' (in the range mentioned in the Matlab code) which has the max CV score)
Screenshot 2021-03-24 at 9 52 45 PM

Closes  #223
@murphyk, @mjsML

### CODE REVIEW

**Review by mjsML — CHANGES_REQUESTED** [review]
The extra library is not required, there are few online examples that implement [RVC](https://github.com/ctgk/PRML) that you [could use](https://github.com/ctgk/PRML/blob/master/notebooks/ch07_Sparse_Kernel_Machines.ipynb).

**Comment by always-newbie161** [comment]
> The extra library is not required, there are few online examples that implement [RVC](https://github.com/ctgk/PRML) that you [could use](https://github.com/ctgk/PRML/blob/master/notebooks/ch07_Sparse_Kernel_Machines.ipynb).
Shoud I import the prml library or  should i implement the RVC in my code😅?
and also Are the methods i mentioned in the PR(above the figures)  fine?

**Comment by mjsML** [comment]
> > The extra library is not required, there are few online examples that implement [RVC](https://github.com/ctgk/PRML) that you [could use](https://github.com/ctgk/PRML/blob/master/notebooks/ch07_Sparse_Kernel_Machines.ipynb).
> 
> Shoud I import the prml library or should i implement the RVC in my code?
> and also Are the methods i mentioned in the PR(above the figures) fine?

Since it's under MIT license, you can use their implementation as reference and implement your own and cite them by adding a link to the original file you used in the python comments something like
```python
# This is a python implementation of foo, it's based on github,com/bar/baz.py 
class foo:
...
```

**Comment by always-newbie161** [comment]
> > > The extra library is not required, there are few online examples that implement [RVC](https://github.com/ctgk/PRML) that you [could use](https://github.com/ctgk/PRML/blob/master/notebooks/ch07_Sparse_Kernel_Machines.ipynb).
> > 
> > 
> > Shoud I import the prml library or should i implement the RVC in my code?
> > and also Are the methods i mentioned in the PR(above the figures) fine?
> 
> Since it's under MIT license, you can use their implementation as reference and implement your own and cite them by adding a link to the original file you used in the python comments something like
> 
> ```python
> # This is a python implementation of foo, it's based on github,com/bar/baz.py 
> class foo:
> ...
> ```

Implemented the RVC.

**Review by murphyk — CHANGES_REQUESTED** [review]
I noticed the original RVC code used np.linalg.inv(H) not your ps_inv function. Did you need your method for numerical stability? Is ps_inv the pseudo inverse? Maybe make it a private method of the class. Also it might be helpful to add a brief note about the underlying algorithm. The code you copies seems to be based on Bishop sec 7.2, which describes the approximate EM algorithm from https://jmlr.csail.mit.edu/papers/v1/tipping01a.html. The E step computes a Laplace (Gaussian) approximation to the weights given alpha, and the M step optimizes the precisions alpha.

Also, the multiple "if i=X" statements inside the for loop for plotting are confusing. It might be simpler to just have separate plotting code for each classifier, even at the cost of some repeated code.

**Comment by always-newbie161** [comment]
> I noticed the original RVC code used np.linalg.inv(H) not your ps_inv function. Did you need your method for numerical stability? Is ps_inv the pseudo inverse? Maybe make it a private method of the class. Also it might be helpful to add a brief note about the underlying algorithm. The code you copies seems to be based on Bishop sec 7.2, which describes the approximate EM algorithm from https://jmlr.csail.mit.edu/papers/v1/tipping01a.html. The E step computes a Laplace (Gaussian) approximation to the weights given alpha, and the M step optimizes the precisions alpha.
> 
> Also, the multiple "if i=X" statements inside the for loop for plotting are confusing. It might be simpler to just have separate plotting code for each classifier, even at the cost of some repeated code.

@murphyk, 
Yes, "ps_inv"  is the psuedo inverse, when I used 'inv' with this dataset it gave me singular matrix error, So I used lstsq(least square method) to estimate the inverse.

Made the required changes.
Hope it is fine.

These are the figures.
Screenshot 2021-03-27 at 2 10 01 PM

Screenshot 2021-03-27 at 2 10 10 PM

**Review by mjsML — APPROVED** [review]

**Pull request merged**
