### PR TITLE
Converted kernelRegressionDemo to python

### LINKED ISSUE #215: Convert kernelRegressionDemo to python
This is figure number 16.10 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/kernelRegressionDemo.m)

### PR DESCRIPTION
**Pull request by always-newbie161**
Figure:
Screenshot 2021-03-25 at 12 55 55 AM

Closes #215
@murphyk, @mjsML

### CODE REVIEW

**Comment by mjsML** [comment]
updated colors as per [updated guidelines](https://github.com/probml/pyprobml/blob/master/CONTRIBUTING.md) image

**Review by mjsML — APPROVED** [review]
Looks good, however is the the [skfda](https://github.com/GAA-UAM/scikit-fda) dependency required?

**Comment by always-newbie161** [comment]
> Looks good, however is the the [skfda](https://github.com/GAA-UAM/scikit-fda) dependency required?

Yes actually (can be installed using "!pip install scikit-fda"), the smoother is present in this package.

**Comment by murphyk** [comment]
This works, but scikit-fda is a big package and slow to install. Is there no light weight solution?

**Comment by always-newbie161** [comment]
> This works, but scikit-fda is a big package and slow to install. Is there no light weight solution?

As I found this as a spot-on function in this package for this problem, I used it to avoid any errors, If needed I would implement it myself using online resources.

**Pull request merged**
