### PR TITLE
FIG: Auto MPG data/tools for figure 1pt1

### PR DESCRIPTION
**Pull request by luisfciencias**
This PR updates the script to generate the first figure (1.1) of the book: 
- [X] Removes code not used and promotes alphabetical imports.
- [X] Test existence of directory of output figures, otherwise generating it.
- [X] Improves parameters to generate box plot figures.

### CODE REVIEW

**Comment by mjsML** [comment]
Hi @luisfciencias , 
I scanned through the PR, can I ask you kindly to explain the change further? 
Thanks in advance,
M

**Comment by luisfciencias** [comment]
Hi @mjsML,
I updated the description. Thanks.

**Comment by mjsML** [comment]
@luisfciencias 

Thank you for updating the description , I went through the code change with your description in mind, and below are my comments by point:
 

1. While alphabetical order imports is part of python coding standards and subsequently linting, removing "unused" code is not necessary as some are intentional for the user to try to uncomment and experiment ... also there is a print statement that I commented and left there , because the print makes the notebooks dependent on that script longer, perhaps debug style checks with some sort of parameter passing mechanism would be better? should be applied to all scripts though for consistency.
  ```python
 if(DEBUG):
    print(df)
``` 
with

  ```console
python script.py --DEBUG=True
``` 

2. That check is never going to fail if you have followed the instructions on the [readme.md](https://github.com/probml/pyprobml/blob/master/README.md) (specifically changing directory to the pyprobml folder)

3. I'd appreciate if you can share a render or screenshot for the difference between the old code and this pull as I could not visually see any difference in a colab notebook (perhaps there is caching or the likes?) 

Please check [Chapter 1 figures notebook](https://colab.research.google.com/github/probml/pyprobml/blob/master/notebooks/figures/chapter1_figures.ipynb) to test your changes.

Thanks,
M

**Comment by luisfciencias** [comment]
Hi @mjsML, 
I think I will wait for the generation of guidelines for pull requests for this repository, otherwise these iterations will generate and propagate misunderstandings between the author's idea of the book in relation to source code to support its structure message and teaching goal. Feel free to ignore and close the PR. Thanks.

**Comment by murphyk** [comment]
I am currently focused on a time-sensitive covid project, but will 'get back to' the book later this Fall.

**Pull request closed without merging**
