### PR TITLE
Latexified Fig15.8 Book2 and converted code to PyMC4

### PR DESCRIPTION
**Pull request by Madhav-Kanda**
### Figure Number

Book2- Fig15.8

### Figures

| Before PR | After Review |
| :-: | :-: |
| image|image| 

### Issue 

#945 

## Steps

- [x] Converted the code to PyMC4
- [x] Latexify

## Checklist:

- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

### CODE REVIEW

**Comment by murphyk** [comment]
Why do we need `%env MKL_THREADING_LAYER=GNU`?

**Comment by Madhav-Kanda** [comment]
Dr. @murphyk, upon running the code in Google Colab without `%env MKL_THREADING_LAYER=GNU`, we encounter the following error: 
image
Thus, to solve this error I have included that line in the code.

**Comment by karm-patel** [comment]
@Madhav-Kanda Can you rename this notebook as `logreg_iris_bayes_2d_pymc.ipynb`? Because I've added blackjax version of the same notebook here: https://github.com/probml/pyprobml/pull/994

**Comment by murphyk** [comment]
There is a conflict in this PR since it tries to delete notebooks/book2/15/logreg_iris_bayes_2d.ipynb

**Comment by karm-patel** [comment]
I'm merging this PR since conflicts are resolved by @Madhav-Kanda.

**Pull request merged**
