### PR TITLE
Convert gaussEvec to python (Issue-189)

### PR DESCRIPTION
**Pull request by shivaditya-meduri**
Python implementation of gaussEvec.m for Figure 7.6.
Figure created by python file shown below:

Figure_1

### CODE REVIEW

**Review by Koenie1980 — APPROVED** [review]

**Comment by animesh-007** [comment]
Fixes #189

**Comment by murphyk** [comment]
In colab, I get the figure below, which looks rather ugly....
Screen Shot 2021-03-19 at 5 14 06 PM

**Comment by shivaditya-meduri** [comment]
Hi @murphyk, Actually the plot isn't wrong, The image I uploaded above is the generated plot, I think the problem is with the dimensions of the plot being different from the Google collab's dimensions of 640x480 which is causing the plot to be cropped at the edges. I will change the dimensions of the plot so that it can display properly on python notebooks as well.

**Review by mjsML — CHANGES_REQUESTED** [review]
The figure doesn't display properly in Google's Colab (which is the primary runtime environment that is used). Please add logic to make the figure as portable as possible (across resolutions and platforms).

**Comment by shivaditya-meduri** [comment]
image

This image is generated using the code in Google collab

@murphyk , Please review the changes that I've made, I fixed the scaling issue and it should work well on all platforms.

**Comment by shivaditya-meduri** [comment]
Thank you for your patience!

**Comment by shivaditya-meduri** [comment]
> The figure doesn't display properly in Google's Colab (which is the primary runtime environment that is used). Please add logic to make the figure as portable as possible (across resolutions and platforms).

Hi @mjsML , Please find the updated code and let me know if there are still problems. I appreciate your time.

**Review by mjsML — APPROVED** [review]

**Comment by mjsML** [comment]
@shivaditya-meduri should the black arrows touch the blue arrows as the original figure?

**Comment by shivaditya-meduri** [comment]
Dear @mjsML , I changed the double arrow to touch the blue line exactly. Thank you for your time

**Comment by shivaditya-meduri** [comment]
image

@mjsML , please let me know if this solves the problem!

**Pull request merged**
