### PR TITLE
plot for fig 30.4 and 30.6

### PR DESCRIPTION
**Pull request by xinglong-li**
add   dp_mixgauss_forward.ipynb   to reproduce fig30.4
add   dp_mixgauss_cluster.ipynb   to reprocuce fig30.6

### CODE REVIEW

**Comment by murphyk** [comment]
this looks good, but it won't run until we finish merging https://github.com/probml/probml-utils/pull/19.

Also please modify the figures to be latexified - see https://docs.google.com/presentation/d/1fz3H_uJwtd-QPRCiCFvP75kKkvLhTiPtsLtWAbbk6ZM/edit#slide=id.g13183a0db9e_0_39

**Comment by xinglong-li** [comment]
Transformed the functions in 
https://ericmjl.github.io/dl-workshop/04-gaussian-clustering/02-dirichlet-processes.html
and 
https://ericmjl.github.io/dl-workshop/04-gaussian-clustering/03-dirichlet-process-clustering.html

**Comment by karm-patel** [comment]
Hi @xinglong-li, can you please fix the first 3 checks, due to failed checks in this PR, checks will keep failing in every upcoming PRs. 

image

**Comment by murphyk** [comment]
@xinglong-li All of these notebooks are broken, which is breaking the automated checks.
I will move them all from notebooks/book2/20 to notebooks/misc, since the notebooks in that directory are not checked.

**Comment by murphyk** [comment]
I have moved all 4 broken DP notebooks from `notebooks/book2/30/` to `notebooks/misc`, since files in that folder are not checked.

**Pull request merged**
