### PR TITLE
gprDemoNoiseFree

### LINKED ISSUE #219: Convert gprDemoNoiseFree to python
This is figure number 17.8 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/gprDemoNoiseFree.m)

### PR DESCRIPTION
**Pull request by nappaillav**
Closes #219

Figure 1) 
image

Figure 2)
image

Figure 3)
image

@mjsML @murphyk

### CODE REVIEW

**Review by mjsML — COMMENTED** [review]
It seems that the figure is different from the one in the book? I haven't looked at the code yet.

**Comment by nappaillav** [comment]
@mjsML I believe that the difference is because of the GaussSample function, because of which there is randomness in the plot.

**Comment by murphyk** [comment]
Please use scipy.spatial.distance.cdist to avoid for loop when computing sq_dist kernel.

**Review by murphyk — CHANGES_REQUESTED** [review]
Please use scipy.spatial.distance.cdist to avoid for loop when computing sq_dist kernel.

**Comment by nappaillav** [comment]
@murphyk updated with cdist

**Pull request merged**
