### PR TITLE
hingeLossPlot.py fixes issue #226

### PR DESCRIPTION
**Pull request by ashishpapanai**
Implemented [https://github.com/probml/pmtk3/blob/master/demos/hingeLossPlot.m](matlab code) to plot hingeLoss in python as mentioned in issue #266
Requesting for review @mjsML 

Plots generated:
Screenshot from 2021-03-12 14-13-35

### CODE REVIEW

**Comment by mjsML** [comment]
This is issue #226

**Comment by mjsML** [comment]
Also @ashishpapanai , this is a duplicate of #237

**Comment by ashishpapanai** [comment]
Hello @mjsML, Should I close this PR as the issue is already resolved in #237? 
Inconvience is regretted.

**Comment by murphyk** [comment]
It turns out I had already converted this to Python myself [script](https://github.com/probml/pyprobml/blob/master/scripts/hinge_loss_plot.py), but I forgot to include it in the latex for the book, so it was accidentally flagged as an open issue.

**Pull request closed without merging**
