### PR TITLE
Simple parallel CI workflow

### PR DESCRIPTION
**Pull request by nalzok**
## Description

Dead simple parallel CI workflow with 20 runners. Feel free to increase the number of concurrent jobs to 40 or something as long as it falls under the [usage limit](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits).

### Issue 

https://github.com/probml/pyprobml/issues/783

## Checklist:

- [X] Performed a self-review of the code
- [X] Tested on Google Colab.

## Potential problems/Important remarks

It's too risky to make use of [actions/cache@v3](https://github.com/actions/cache) without pinning the exact version of all packages, so this PR only implements parallel CI.

### CODE REVIEW

**Comment by patel-zeel** [comment]
Nice trick using environment variable! Currently, all the other jobs are cancelled if one of them is failed. Shall we disable [fail-fast](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures)? 

I really like the idea of exetuting newer notebooks first because it saves lot of time of developers. Is it possible to implement that?

**Comment by nalzok** [comment]
Hi @patel-zeel, it has been done! The notebooks are sorted by their modification time so that the most recently touched notebook is executed by job number 0, while the second most recently touched one is executed by job number 1, etc.

It took me a few commits to debug on the CI environment, but I have squashed the redundant commits with `git rebase` so that your commit log won't be polluted.

**Comment by patel-zeel** [comment]
This looks great, @nalzok! I will soon create an automated dashboard to easily view the status and logs from the failing notebooks.

**Comment by patel-zeel** [comment]
@nalzok I think it is difficult to get such workflows right in one commit so it is fine if there are multiple commits. This repo has only the "squash and merge" option so the commit log won't be polluted.

**Pull request merged**
