### PR TITLE
Create riskFnGauss.py

### LINKED ISSUE #184: Convert riskFnGauss to python
This is figure number 5.13 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/riskFnGauss.m)

### PR DESCRIPTION
**Pull request by Garvit9000c**
Closes #184 
neymanPearson2(20)
neymanPearson2(5)

### CODE REVIEW

**Comment by Garvit9000c** [comment]
> #184 
This issue should be closed with merging of this pull request.

**Review by mjsML — CHANGES_REQUESTED** [review]
Please separate the two plots into two pngs or pdfs, use the right name for each (you are reusing the name of the old pull request).

**Comment by Garvit9000c** [comment]
Ok sir , Done

**Review by mjsML — APPROVED** [review]
looks good to me.

**Comment by ashishpapanai** [comment]
@Garvit9000c Could you please mention the issue in the PR description as well so that it's mentioned on the issue page? 
You can do so by writing:
Closes #184

**Comment by Garvit9000c** [comment]
@ashishpapanai I have already mentioned it.
Take a look at second comment, or do you mean something else?

**Comment by ashishpapanai** [comment]
@Garvit9000c If we mention the issue as 'Closes #Number' on the PR description then on the issue page, the PR is mentioned with the issue this saves time while someone is finding an issue to work on.

**Comment by Garvit9000c** [comment]
That's insightful, I will follow the convention now onwards!

**Comment by mjsML** [comment]
@Garvit9000c @ashishpapanai means this [github feature](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Pull request merged**
