### PR TITLE
Figure 3.10

### PR DESCRIPTION
**Pull request by Abdelrahman350**
Hello, I added a Python file to plot figure 3.10's two graphs.

### CODE REVIEW

**Comment by Abdelrahman350** [comment]
Figure 3.10

**Review by mjsML — APPROVED** [review]
Looks good to me 🙂

**Review by murphyk — CHANGES_REQUESTED** [review]
Can you please make the 3d surface plot be aligned with the 2d contour plot, similar to the original figure? (I think you just have to change the viewing angle)

**Comment by Abdelrahman350** [comment]
> Can you please make the 3d surface plot be aligned with the 2d contour plot, similar to the original figure? (I think you just have to change the viewing angle)
Yes, of course, I will do it.

**Comment by Abdelrahman350** [comment]
> Can you please make the 3d surface plot be aligned with the 2d contour plot, similar to the original figure? (I think you just have to change the viewing angle)

Alright, I pushed the changes and waiting for your approval @murphyk.

**Comment by mjsML** [comment]
@Abdelrahman350 , you are including figure 4.20 in the same pull request #181

**Comment by Abdelrahman350** [comment]
> @Abdelrahman350 , you are including figure 4.20 in the same pull request #181 

Do you want me to make a new pull request?

**Comment by mjsML** [comment]
@Abdelrahman350 yes please so it's clear to everyone what is being changed and which issue is being closed.

**Comment by Abdelrahman350** [comment]
> @Abdelrahman350 yes please so it's clear to everyone what is being changed and which issue is being closed.

Ok, I will make a new pull request.

**Comment by mjsML** [comment]
> > @Abdelrahman350 yes please so it's clear to everyone what is being changed and which issue is being closed.
> 
> Ok, I will make a new pull request.

Thanks, can I ask you to delete the other figure file from this pull request? (by deleting the file and then committing again to the same branch)

**Comment by mjsML** [comment]
Or by undoing the commit.

**Comment by Abdelrahman350** [comment]
> > > @Abdelrahman350 yes please so it's clear to everyone what is being changed and which issue is being closed.
> > 
> > 
> > Ok, I will make a new pull request.
> 
> Thanks, can I ask you to delete the other figure file from this pull request? (by deleting the file and then committing again to the same branch)

Ok, it was done

**Pull request merged**
