### PR TITLE
Converted linregRbfDemo to python

### LINKED ISSUE #212: Convert linregRbfDemo to python
This is figure number 13.24 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/linregRbfDemo.m)

### PR DESCRIPTION
**Pull request by always-newbie161**
Figure generated.

Screenshot 2021-03-27 at 10 36 45 PM

Closes #212
@mjsML @murphyk

### CODE REVIEW

**Comment by nappaillav** [comment]
@always-newbie161 I was working on this, PR #306 . But anyways no issues, you can change the plot colormap according to the contribution guidelines. 
:)

**Comment by always-newbie161** [comment]
> @always-newbie161 I was working on this, PR #306 . But anyways no issues. You can change the plot colormap according to the contribution guidelines.
> :)

Oo yeah I was aware of it 😅, but as the PR is closed, I continued to work on it. I am sorry which guideline are you referring for?

**Comment by nappaillav** [comment]
@always-newbie161 [Contribution guidelines](https://github.com/probml/pyprobml/blob/master/CONTRIBUTING.md)
As mentioned in guidelines "Please don't hardcode colors of your figure, use the default values. If you need to manually choose colors, use the new default colormap of matplotlib."
Pick colors from [matplotlib's viridis colormap](https://matplotlib.org/stable/users/dflt_style_changes.html#colormap)

**Comment by always-newbie161** [comment]
@nappaillav, thankyou 👍

**Comment by nappaillav** [comment]
@always-newbie161  
The imagesc plot is quite squashed you can use `plt.imshow(matrix, interpolation='nearest', aspect='auto')` to correct the aspect ratio and the plot color are still hard coded, For example Line 58 and Line. 64. instead if want to specify the, then  you can make use of the follow color pallet (these color can be visually differentiated by color blind people). 
```
CB_color = ['#377eb8', '#ff7f00', '#4daf4a',
            '#f781bf', '#a65628', '#984ea3',
            '#999999', '#e41a1c', '#dede00']
```
These were the suggestions given to me while I submitted the draft for this issue. So I just wanted to pass down the information to you. But you can verify this with @mjsML and make the changes (so that you can push all your changes in fewer commits). 
:)

**Comment by always-newbie161** [comment]
@nappaillav, thankyou for giving the suggestions, added a color cycle using the given pallet.

@mjsML, Can you confirm whether it works, if not, would like to make any changes,

Screenshot 2021-03-28 at 8 52 17 PM

**Comment by murphyk** [comment]
This code is incorrect - you use a Gaussian process, which has N centroids centered on the data, but the book says that it is doing linear regression on an RBF feature set with K centroids chosen by the user. Please follow the [matlab code](https://github.com/probml/pmtk3/blob/master/demos/linregRbfDemo.m).

**Comment by always-newbie161** [comment]
@murphyk, Changed it to Kernel ridge(uses l2 regularization with linear reg) which is trained using a rbf feature set generated with "centers" as centroids and "xtrain" as training data.

Fugures may seem to be different from the reference ones, but they are consistent with the description mentioned in Para.13.6.1.1 in the book.

Screenshot 2021-03-30 at 11 48 25 AM

**Comment by murphyk** [comment]
Please just use regular linear (or maybe ridge) regression on your rbf design matrix, not kernel ridge regression.
The model you are fiting should have the form
p(y|x, θ) = N (w' φ(x), σ^2).
which is linear in w, where phi(x) is your expanded feature vector.

**Comment by always-newbie161** [comment]
> Please just use regular linear (or maybe ridge) regression on your rbf design matrix, not kernel ridge regression.
> The model you are fiting should have the form
> p(y|x, θ) = N (w' φ(x), σ^2).
> which is linear in w, where phi(x) is your expanded feature vector.

Hi @murphyk, I realised my mistake now, changed it to ridge regression

**Review by mjsML — APPROVED** [review]

**Comment by murphyk** [comment]
Next time, please use `pml.save_fig("../figures/rbfDemoALL.pdf", dpi=300)`

**Pull request merged**
