### PR TITLE
Added implementation for kpcaScholkopf

### LINKED ISSUE #232: Convert kpcaScholkopf to python
This is figure number 20.35 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/kpcaScholkopf.m)

### PR DESCRIPTION
**Pull request by animesh-007**
Added python implement for kpcaScholkopf.py
Fixes #232 
Screen Shot 2021-03-18 at 10 03 05 PM

### CODE REVIEW

**Comment by animesh-007** [comment]
@mjsML @murphyk I have a small doubt. In this problem, eigenvalues are dependent on the random number generator because of which I'm not able to get same eigenvalues. Let me know if this is okay, if not I will  copy matlab random number 
array in my code or you could suggest me something better.

**Comment by murphyk** [comment]
Don't worry about the random seed, the results look fine.
However please eliminate the double for loop (for i, for j) and use 
scipy.spatial.distance.pdist to compute the Gram matrix.

**Comment by animesh-007** [comment]
> Don't worry about the random seed, the results look fine.
> However please eliminate the double for loop (for i, for j) and use
> scipy.spatial.distance.pdist to compute the Gram matrix.

Made suggested changes.

**Review by mjsML — APPROVED** [review]
Looks good to me.

**Pull request merged**
